'use client';

import { useEffect } from 'react';
import AOS from 'aos';
import 'aos/dist/aos.css';

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

// Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// // Metadata
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // Initialize AOS
  useEffect(() => {
    AOS.init({
      duration: 800,       // animation duration in ms
      once: false,          // animate only once
      easing: 'ease-in-out' // smooth transition
    });
  }, []);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Header */}
        <div data-aos="fade-down">
          <Header />
        </div>

        {/* Main content */}
        <div data-aos="fade-up">
          {children}
        </div>

        {/* Footer */}
        <div data-aos="fade-up">
          <Footer />
        </div>
      </body>
    </html>
  );
}
