import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Fixed Header */}
        {/* <div >
          <Header />
        </div> */}

        {/* Main content area with space for header & footer */}
        <div >
          {children}
        </div>

        {/* Fixed Footer */}
        <div >
          <Footer />
        </div>
      </body>
    </html>
  );
}


// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Header from "@/components/Header";
// import UserHeader from "@/components/UserHeader"; // import your user header
// import Footer from "@/components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   // dummy authentication flag (replace later with real auth state)
//   const user = false; // change to true to test UserHeader

//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {/* Fixed Header */}
//         <div>
//           {user ? <UserHeader /> : <Header />}
//         </div>

//         {/* Main content area with space for header & footer */}
//         <div>
//           {children}
//         </div>

//         {/* Fixed Footer */}
//         <div>
//           <Footer />
//         </div>
//       </body>
//     </html>
//   );
// }
